import { PRESETS } from "../net/presets";
import {
  JEV_SUMMARY_VERIFY_SCOPE,
  LLM_CONSENT_SCOPES,
  LLM_ESCALATE_SCOPE,
  LLM_EXPLAIN_SCOPE,
  LLM_RESTRUCTURE_SCOPE,
  LLM_SUMMARY_SCOPE,
  LLM_TEST_SCOPE,
  type LlmConsentScope,
  type PresetId,
} from "../schemas/provider";

/**
 * The in-product consent disclosure copy (PROJECT_PLAN.md §13.5, spec §3).
 * Everything the Options screen must name before consent lives here as typed
 * constants so `ProviderSetup` renders it and tests assert its presence: the
 * recipient, the literal origin, the exact synthetic fields, the
 * authorization header, the purpose, the trigger, and the privacy-policy
 * links. Origins come from the frozen preset registry so the disclosure can
 * never drift from the destinations the gate allows.
 */

/** Top-level field names of the fixed synthetic `jev_test` request body. */
export const SYNTHETIC_FIELDS = ["model", "state", "questions"] as const;

/** The only header that ever carries the API key to the provider. */
export const AUTHORIZATION_HEADER = "Authorization";

/** Why the synthetic request exists — the reason disclosed before consent. */
export const CONSENT_PURPOSE =
  "check that your API key and the provider's Jev endpoint respond, using a fixed synthetic request that contains no bookmark data";

/**
 * When data may flow — the trigger disclosed before consent. Enabling only
 * grants the browser permission and stores consent locally; a request can
 * leave the device only on an explicit Test connection action.
 */
export const CONSENT_TRIGGER =
  'only when you click "Test connection" — never on install, on page load, in the background, or when enabling the provider';

/** What the synthetic request is made of — disclosed before consent. */
export const SYNTHETIC_DESCRIPTION =
  "a fixed, synthetic test payload generated by the extension — it contains no bookmark titles, URLs, notes, or page content";

/** Per-provider disclosure facts. */
export interface ProviderDisclosure {
  /** Human-readable recipient name. */
  readonly name: string;
  /** The literal canonical origin that receives the request. */
  readonly origin: string;
  /** The provider's own privacy policy (governs data it receives). */
  readonly privacyPolicyUrl: string;
  /** Provider data-handling note surfaced to the user (§8.5 step 7). */
  readonly dataNote: string;
}

export const PROVIDER_DISCLOSURES = {
  typesafe: {
    name: "TypeSafe",
    origin: PRESETS.typesafe.origin,
    // Canonical policy URL — /privacy 308-redirects to /legal/privacy-policy
    // (verified 2026-09-27).
    privacyPolicyUrl: "https://typesafe.ai/legal/privacy-policy",
    dataNote:
      "TypeSafe states that Jev is not trained on customer requests; zero data retention is available on enterprise plans.",
  },
  openrouter: {
    name: "OpenRouter",
    origin: PRESETS.openrouter.origin,
    privacyPolicyUrl: "https://openrouter.ai/privacy",
    dataNote:
      "OpenRouter forwards Jev requests to TypeSafe; the data policy on the OpenRouter model page applies.",
  },
} as const satisfies Record<PresetId, ProviderDisclosure>;

// --- `jev_decisions` bookmark-metadata disclosure ------------------------
// The per-provider consent that covers every Phase 4 decision feature
// (PROJECT_PLAN.md §13.4/§13.5, spec FR1/FR11). These typed constants are the
// single source of truth: `ProviderSetup` renders them, the store docs quote
// them nearly verbatim, and `tests/unit/consent-snapshot.test.ts` pins them
// (§13.12) so a change to the sent fields cannot ship without a
// `CONSENT_VERSION` bump and matching `store/` edits.

/**
 * The exact bookmark facts a `jev_decisions` request may carry, in the order
 * the disclosure lists them. Every label maps to a populated field of the
 * closed `DecisionState` schema (`src/schemas/decision-state.ts`); the
 * snapshot test fails if a `DecisionState` field has no label here.
 */
export const DECISIONS_SENT_FIELDS = [
  "bookmark title",
  "cleaned URL",
  "domain",
  "folder path",
  "tag names and descriptions",
  "candidate folder paths",
  "candidate bookmarks",
  "near-duplicate partner",
  "Ask search query",
] as const;

/**
 * Content that is never sent under any scope. Named explicitly so the
 * disclosure states the negative as plainly as the positive (plan §13.4:
 * notes and page text never leave the device).
 */
export const DECISIONS_NEVER_SENT_FIELDS = ["notes", "page text"] as const;

/** Why bookmark metadata is sent — the reasons disclosed before consent. */
export const DECISIONS_PURPOSES = [
  "categorize",
  "tag",
  "folder pre-select",
  "near-duplicate check",
  "misfiled scan",
  "search re-rank",
] as const;

/**
 * The user actions that may start a `jev_decisions` request. Every trigger is
 * user-started; nothing runs on install, on a timer, or in the background.
 */
export const DECISIONS_TRIGGERS = [
  "saving a bookmark",
  "clicking Analyze",
  "starting a library scan",
  "running an Ask search",
] as const;

/** The user-started-only guarantee, stated in full for the disclosure. */
export const DECISIONS_TRIGGER_NOTE =
  "only when you start them — never on install, on a timer, or in the background";

/** What the `jev_decisions` request is made of — disclosed before consent. */
export const DECISIONS_DESCRIPTION =
  "bookmark metadata only — no notes and no page text, which are never sent under any scope";

/** How the extension's own privacy policy is referenced before a public URL exists. */
export const EXTENSION_PRIVACY_POLICY_REFERENCE =
  "this extension's privacy policy";

// --- Phase 5: dynamic LLM provider disclosures ---------------------------
// One typed disclosure per LLM consent scope (spec §3, FR2.8). The recipient
// is the *configured* provider — not a preset — so the disclosure states
// purpose, fields, trigger, and credential use provider-agnostically, and the
// Options UI injects the resolved origin at render time. The snapshot test
// pins every field label so a schema change cannot ship undisclosed.

export { LLM_CONSENT_SCOPES };

/** Content no LLM scope may ever send. */
export const LLM_NEVER_SENT = [
  "notes",
  "the full page DOM",
  "credentials in the message body",
] as const;

/** How the stored credential travels to the LLM provider. */
export const LLM_CREDENTIAL_USE =
  "your stored provider credential goes in the request's authentication header only — never inside the message body";

/** How the stored Jev credential travels for the summary verification call. */
export const JEV_CREDENTIAL_USE =
  "your stored Jev credential goes in the request's Authorization header only — never inside the message body";

/** Per-scope disclosure facts for the optional LLM provider. */
export interface LlmScopeDisclosure {
  /** Short feature name shown on the consent card. */
  readonly title: string;
  /** Why the request exists — the reason disclosed before consent. */
  readonly purpose: string;
  /** The exact facts the request may carry, in disclosure order. */
  readonly fields: readonly string[];
  /** The user action that may start this request. */
  readonly trigger: string;
  /** How the credential travels when the provider requires one. */
  readonly credentialUse: string;
}

export const LLM_SCOPE_DISCLOSURES = {
  [LLM_TEST_SCOPE]: {
    title: "LLM test connection",
    purpose:
      "check that your credentials and the provider's OpenAI-compatible endpoint respond, using a fixed synthetic request containing no bookmark or page data",
    fields: ["model", "messages", "response_format"],
    trigger: 'only when you click "Test connection"',
    credentialUse: LLM_CREDENTIAL_USE,
  },
  [LLM_EXPLAIN_SCOPE]: {
    title: "Decision explanations",
    purpose: "explain a review-queue decision in plain language",
    fields: [
      "decision state",
      "question",
      "candidate labels",
      "Jev probabilities",
      "selected answer",
    ],
    trigger: 'only when you click "Explain" on a pending decision',
    credentialUse: LLM_CREDENTIAL_USE,
  },
  [LLM_ESCALATE_SCOPE]: {
    title: "Automatic second opinions",
    purpose: "give a second opinion on a low-confidence Jev decision",
    fields: [
      "decision state",
      "question",
      "allowed options",
      "Jev probabilities",
      "Jev answer",
    ],
    trigger:
      "only inside a Save, Analyze, or library scan you started, when the Jev answer fell in the low-confidence band and your monthly budget allows it",
    credentialUse: LLM_CREDENTIAL_USE,
  },
  [LLM_RESTRUCTURE_SCOPE]: {
    title: "Restructure proposals",
    purpose: "propose a folder structure for your library",
    fields: [
      "folder paths",
      "category counts",
      "tag counts",
      "domains",
      "representative titles (capped)",
    ],
    trigger: 'only when you start "Restructure"',
    credentialUse: LLM_CREDENTIAL_USE,
  },
  [LLM_SUMMARY_SCOPE]: {
    title: "Page summaries",
    purpose: "summarize the current page for a saved bookmark",
    fields: ["page title", "site name", "headings", "bounded page excerpt"],
    trigger:
      'only when you click "Summarize" — the page is extracted only after that click',
    credentialUse: LLM_CREDENTIAL_USE,
  },
  [JEV_SUMMARY_VERIFY_SCOPE]: {
    title: "Jev summary verification",
    purpose:
      "verify that an LLM summary is supported by the extracted page text",
    fields: [
      "page title",
      "bounded page excerpt",
      "LLM-generated summary",
    ],
    trigger: "only as part of a Summarize action you started",
    credentialUse: JEV_CREDENTIAL_USE,
  },
} as const satisfies Record<LlmConsentScope, LlmScopeDisclosure>;
