import { PRESETS } from "../net/presets";
import type { PresetId } from "../schemas/provider";

/**
 * The in-product consent disclosure copy (PROJECT_PLAN.md §13.5, spec §3).
 * Everything the Options screen must name before consent lives here as typed
 * constants so `ProviderSetup` renders it and tests assert its presence: the
 * recipient, the literal origin, the exact synthetic fields, the
 * authorization header, the purpose, the trigger, and the privacy-policy
 * links. Origins come from the frozen preset registry so the disclosure can
 * never drift from the destinations the gate allows.
 */

/** Top-level field names of the fixed synthetic `jev_test` request body. */
export const SYNTHETIC_FIELDS = ["model", "state", "questions"] as const;

/** The only header that ever carries the API key to the provider. */
export const AUTHORIZATION_HEADER = "Authorization";

/** Why the synthetic request exists — the reason disclosed before consent. */
export const CONSENT_PURPOSE =
  "check that your API key and the provider's Jev endpoint respond, using a fixed synthetic request that contains no bookmark data";

/**
 * When data may flow — the trigger disclosed before consent. Enabling only
 * grants the browser permission and stores consent locally; a request can
 * leave the device only on an explicit Test connection action.
 */
export const CONSENT_TRIGGER =
  'only when you click "Test connection" — never on install, on page load, in the background, or when enabling the provider';

/** What the synthetic request is made of — disclosed before consent. */
export const SYNTHETIC_DESCRIPTION =
  "a fixed, synthetic test payload generated by the extension — it contains no bookmark titles, URLs, notes, or page content";

/** Per-provider disclosure facts. */
export interface ProviderDisclosure {
  /** Human-readable recipient name. */
  readonly name: string;
  /** The literal canonical origin that receives the request. */
  readonly origin: string;
  /** The provider's own privacy policy (governs data it receives). */
  readonly privacyPolicyUrl: string;
  /** Provider data-handling note surfaced to the user (§8.5 step 7). */
  readonly dataNote: string;
}

export const PROVIDER_DISCLOSURES = {
  typesafe: {
    name: "TypeSafe",
    origin: PRESETS.typesafe.origin,
    // Canonical policy URL — /privacy 308-redirects to /legal/privacy-policy
    // (verified 2026-09-27).
    privacyPolicyUrl: "https://typesafe.ai/legal/privacy-policy",
    dataNote:
      "TypeSafe states that Jev is not trained on customer requests; zero data retention is available on enterprise plans.",
  },
  openrouter: {
    name: "OpenRouter",
    origin: PRESETS.openrouter.origin,
    privacyPolicyUrl: "https://openrouter.ai/privacy",
    dataNote:
      "OpenRouter forwards Jev requests to TypeSafe; the data policy on the OpenRouter model page applies.",
  },
} as const satisfies Record<PresetId, ProviderDisclosure>;
